[package]
name = "gase-sound"
description = "Yamaha YM2612 FM synthesiser and TI SN76489 PSG (part of the gase Mega Drive emulator)"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
gase-savestate.workspace = true

[lints]
workspace = true
